name: Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }} - ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macOS-latest
            arch: arm64
          - os: macOS-latest
            arch: x64
          - os: windows-latest
            arch: x64
          - os: ubuntu-latest
            arch: x64

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: npm ci
      - name: Make
        run: npm run make -- --arch=${{ matrix.arch }}
        shell: bash
        env:
          IS_CODESIGNING_ENABLED: "false"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clippy-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            out/**/*.zip
            out/**/*.deb
            out/**/*.rpm
            out/**/*setup*.exe
